chg:pkg: Upgrade setup process and instructions (2nd try)
Finally fix #797

* enhance README.md to match current PyPA install process
* improve and expand pyproject.toml
  * build requires section
  * build excludes section
* improve and shrink setup.py
  * remove SdistCommand
  * suppress nonsense warnings
* pyproject.toml now does most of the heavy lifting
* requires updates to pip, pipx, and setuptools
  * the newer pip builds a virtual environment
  * it installs the build requirements in that venv
  * the build is then done in that venv
* fixes to tools/install\* scripts to build/test VM environment
* replaces argparse with duplicity/argparse311 globally

diff --git a/tools/testpip b/tools/testpip
--- a/tools/testpip
+++ b/tools/testpip
@@ -39,24 +39,49 @@ VERS="3.8 3.9 3.10 3.11 3.12"
 # We use pyenv to make a reproducible environment for multiple versions.
 # See: https://github.com/pyenv/pyenv/ for links and install commands.
 
+trap cleanup EXIT ERR
+
+cleanup ()
+{
+    pyenv global system
+    sudo rm -rf dist build duplicity.egg-info
+    echo "Cleanup done"
+}
+
 # test sdist build and install on each version
 for V in ${VERS}; do
     echo "Testing sdist on Python$V"
     pyenv global $V
     python$V -m build --sdist
-    python$V -m pip install dist/duplicity-*.tar.gz
-    echo "----------"
+    python$V -m pip -q install dist/duplicity-*.tar.gz
+    echo -e "\n----------"
     cd ..
-    python$V -m duplicity -V
-    duplicity -V
+    # test duplicity as module
+    res=$(python$V -m duplicity -V)
+    if [[ "$res" == "duplicity ${VERSION}"* ]]; then
+        echo "duplicity as module passed."
+    else
+        echo "duplicity as module failed."
+        echo "$res"
+        exit 1
+    fi
+    # test duplicity as script
+    res=$(duplicity -V)
+    if [[ "$res" == "duplicity ${VERSION}"* ]]; then
+        echo "duplicity as script passed."
+    else
+        echo "duplicity as script failed."
+        echo "$res"
+        exit 1
+    fi
     cd -
-    echo "----------"
+    echo -e "----------\n"
 done
 
 # get wheels from last good run of wheels job
 BRANCH=main
 JOB=wheels
-echo "Downloading artifacts from branch ${BRANCH} job ${JOB}"
+echo "Downloading artifacts.zip from branch ${BRANCH} job ${JOB}"
 curl --location "https://gitlab.com/api/v4/projects/12450835/jobs/artifacts/${BRANCH}/download?job=${JOB}"  \
      --output /tmp/artifacts.zip
 unzip -o /tmp/artifacts.zip
@@ -67,12 +92,12 @@ for V in ${VERS}; do
     pyenv global $V
     python$V -m pip uninstall -y duplicity
     python$V -m pip install wheelhouse/duplicity-*-cp${V//.}-*.whl
-    echo "----------"
+    echo -e "\n----------"
     cd ..
     python$V -m duplicity -V
     duplicity -V
     cd -
-    echo "----------"
+    echo -e "----------\n"
 done
 
 pyenv global system
